version: '3'
services:
  envoy:
    image: envoyproxy/envoy-dev
    depends_on:
      - svc01
      - svc02
    ports:
      - "9001:10000"
      - "10001:10001"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
  haproxy:
    image: haproxy:alpine
    depends_on:
      - svc01
      - svc02
    ports:
      - "9002:10000"
      - "10002:9090"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
  nginx:
    image: nginx
    depends_on:
      - svc01
      - svc02
    volumes:
     - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
     - "9003:80"
    environment:
     - NGINX_PORT=80

  svc01:
    image: nginx
    volumes:
      - ./svc01.html:/usr/share/nginx/html/index.html

  svc02:
    image: nginx
    volumes:
      - ./svc02.html:/usr/share/nginx/html/index.html